name = "FEHM"
uuid = "08f7bda6-d19a-5869-bd1c-a698fdb2a278"
version = "0.3.0"

[deps]
DocumentFunction = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
DocumentFunction = "1"
FileIO = "1"
JLD = "0.12, 0.13"
JLD2 = "0.2, 0.3"
WriteVTK = "1"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
